INSERT INTO tb_livro (nomeLivro, sinopse, id_editora, id_genero, id_autor) VALUES 
('Dom Casmurro', 'Um romance psicológico sobre ciúme e traição.', 1, 1, 2),
('A Hora da Estrela', 'A história de uma jovem nordestina em busca de uma vida melhor no Rio de Janeiro.', 2, 1, 5),
('Capitães da Areia', 'A vida de meninos de rua na Bahia.', 3, 1, 6),
('Percy Jackson e o Ladrão de Raios', 'A primeira aventura de Percy Jackson, um semideus moderno.', 4, 4, 1),
('Harry Potter e a Pedra Filosofal', 'O início das aventuras de Harry Potter em Hogwarts.', 5, 4, 5),
('Game of Thrones', 'Intrigas e batalhas pelo controle do Trono de Ferro em Westeros.', 6, 4, 6),
('O Senhor dos Anéis: A Sociedade do Anel', 'A primeira parte da épica trilogia de fantasia de Tolkien.', 7, 4, 7),
('Assassinato no Expresso do Oriente', 'Hercule Poirot investiga um assassinato em um trem luxuoso.', 8, 6, 8),
('O Iluminado', 'Uma história de terror sobre um hotel assombrado e um homem perturbado.', 9, 5, 9),
('Deuses Americanos', 'Um ex-presidiário é arrastado para uma batalha entre os deuses antigos e novos.', 10, 4, 10),
('Orgulho e Preconceito', 'Um romance sobre amor e convenções sociais na Inglaterra do século XIX.', 11, 1, 11),
('Fundação', 'Uma épica série de ficção científica sobre a queda e ascensão de um império galáctico.', 12, 2, 12),
('Frankenstein', 'A história de um cientista que cria um ser vivo a partir de partes de corpos humanos.', 13, 5, 13),
('O Conto da Aia', 'Uma distopia sobre uma sociedade totalitária que subjuga as mulheres.', 14, 4, 14),
('O Velho e o Mar', 'A luta épica de um pescador idoso contra um grande peixe marinho.', 15, 11, 15),
('As Aventuras de Huckleberry Finn', 'A jornada de um jovem rapaz e um escravo fugitivo pelo rio Mississippi.', 16, 7, 16),
('O Grande Gatsby', 'A história trágica do misterioso milionário Jay Gatsby e seu amor por Daisy Buchanan.', 17, 11, 17),
('Norwegian Wood', 'Um jovem é confrontado com memórias de amor e perda na década de 1960 no Japão.', 18, 11, 18),
('Cem Anos de Solidão', 'A saga épica da família Buendía em Macondo.', 19, 4, 19),
('Amada', 'A história de uma ex-escrava assombrada pelas lembranças de seu passado.', 20, 1, 20),
('A Menina que Roubava Livros', 'A história de uma jovem garota que encontra consolo na leitura durante a Segunda Guerra Mundial.', 1, 11, 2),
('O Nome do Vento', 'A primeira parte da trilogia "A Crônica do Matador do Rei".', 2, 4, 4),
('O Código Da Vinci', 'Um thriller que segue o professor de simbologia Robert Langdon em uma caçada por segredos ocultos.', 3, 7, 5),
('Os Homens que Não Amavam as Mulheres', 'O primeiro livro da série Millennium, um thriller de mistério e suspense.', 4, 6, 6),
('A Sombra do Vento', 'Um romance misterioso ambientado na Barcelona da pós-guerra.', 5, 11, 7),
('O Caçador de Pipas', 'A emocionante história de amizade e redenção no Afeganistão.', 6, 11, 8),
('Cem Anos de Solidão', 'A saga épica da família Buendía em Macondo.', 7, 1, 19),
('A Revolução dos Bichos', 'Uma fábula política sobre os perigos do totalitarismo.', 8, 16, 6),
('1984', 'Uma distopia sobre um futuro sombrio sob um regime totalitário.', 9, 16, 9),
('O Apanhador no Campo de Centeio', 'A história de Holden Caulfield, um adolescente em busca de sentido.', 10, 11, 10),
('O Hobbit', 'A jornada de Bilbo Bolseiro em uma aventura épica para recuperar um tesouro roubado.', 11, 4, 7),
('Crime e Castigo', 'Um romance psicológico sobre a moralidade e o crime.', 12, 11, 11),
('Guerra e Paz', 'Um épico sobre a sociedade russa durante as Guerras Napoleônicas.', 13, 11, 12),
('Lolita', 'A controversa história de amor e obsessão de Humbert Humbert.', 14, 11, 13),
('Ulisses', 'Uma reimaginação moderna da Odisseia de Homero.', 15, 11, 14),
('Moby Dick', 'A obsessiva caça do Capitão Ahab pela baleia branca.', 16, 11, 15),
('A Divina Comédia', 'A jornada épica de Dante Alighieri pelo Inferno, Purgatório e Paraíso.', 17, 11, 16),
('O Morro dos Ventos Uivantes', 'Uma história de amor e vingança na charneca inglesa.', 18, 1, 17),
('O Grande Gatsby', 'A história trágica do misterioso milionário Jay Gatsby e seu amor por Daisy Buchanan.', 19, 1, 18),
('Jane Eyre', 'A vida de uma jovem órfã que supera adversidades para encontrar seu lugar no mundo.', 20, 1, 19),
('As Crônicas de Nárnia: O Leão, a Feiticeira e o Guarda-Roupa', 'A história mágica de quatro irmãos que encontram um mundo encantado.', 21, 4, 20),
('O Guia do Mochileiro das Galáxias', 'Uma comédia de ficção científica sobre as aventuras de Arthur Dent no espaço.', 22, 2, 12),
('O Pequeno Príncipe', 'Uma fábula poética sobre a vida e a humanidade.', 23, 14, 13),
('Anna Kariênina', 'Um romance sobre amor e tragédia na sociedade russa.', 24, 1, 14),
('O Senhor das Moscas', 'A luta pela sobrevivência de um grupo de meninos em uma ilha deserta.', 25, 1, 15),
('O Senhor dos Anéis: As Duas Torres', 'A segunda parte da épica trilogia de Tolkien.', 26, 4, 7),
('O Senhor dos Anéis: O Retorno do Rei', 'A conclusão da épica trilogia de Tolkien.', 27, 4, 7),
('O Conde de Monte Cristo', 'A vingança de Edmond Dantès contra aqueles que o traíram.', 28, 11, 16),
('Drácula', 'A luta contra o lendário vampiro Conde Drácula.', 29, 5, 17),
('A Metamorfose', 'A história de Gregor Samsa, que acorda transformado em um inseto gigante.', 30, 11, 18),
('O Processo', 'A história de Josef K., que é preso e julgado por um crime desconhecido.', 31, 11, 18),
('Don Quixote', 'As aventuras do cavaleiro errante Dom Quixote e seu fiel escudeiro Sancho Pança.', 32, 11, 19),
('Madame Bovary', 'A trágica vida de Emma Bovary e sua busca por paixão e emoção.', 33, 11, 20),
('O Estrangeiro', 'A história de Meursault, um homem indiferente que comete um assassinato sem motivo aparente.', 34, 11, 19),
('O Jogo do Anjo', 'Um jovem escritor recebe uma oferta misteriosa que mudará sua vida para sempre.', 35, 11, 7),
('O Menino do Pijama Listrado', 'A inocente amizade entre dois garotos durante o Holocausto.', 36, 11, 6),
('A Cabana', 'Um homem encontra respostas para suas questões mais profundas em uma cabana misteriosa.', 37, 11, 6),
('A Menina que Brincava com Fogo', 'A continuação da série Millennium, com mais mistérios e suspense.', 8, 6, 21),
('A Rainha Vermelha', 'Uma jovem descobre poderes especiais e se vê no meio de uma guerra de classes.', 9, 4, 22),
('A Dança dos Dragões', 'O quinto livro da série "As Crônicas de Gelo e Fogo", cheio de intrigas e batalhas.', 10, 4, 23);



